# ADS NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

*Note:*
### WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
### BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
### BE ABLE TO SEE THE OUTPUT ANY MORE

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [11]:
nums = np.array([5,5,5,5,5,5,5,5,5,5])
print(nums)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [14]:
nums = np.arange(10, 51)
nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [17]:
nums = np.arange(10,51,2)
print(nums)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
twodim = np.array([[0,1,2], [3,4,5], [6,7,8]])
twodim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [19]:
idn = np.eye(3)
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [36]:
random = np.random.normal(0,1,1)
print(random)

[0.95238128]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [38]:
random = np.random.normal(0,1,25)
print(random)

[ 1.31918394  1.14472661  0.47975638 -1.73115524 -0.87497598 -0.45462974
  0.06181195  0.03139242 -0.68350952 -0.70339337 -0.01475748  1.39908643
  0.65290891  0.03484032 -0.37068406 -0.69115253  0.54701151 -0.46119751
  0.41359902 -0.39898829 -1.83255138  1.62444568  0.29029205  0.50250045
  0.2346941 ]


#### Create the following matrix:

In [41]:
zero_to_1 = np.linspace(0, 1, 100)
zero_to_1

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

#### Create an array of 20 linearly spaced points between 0 and 1:

In [4]:
zero_to_1 = np.linspace(0, 1, 20)
zero_to_1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [5]:
nums2d = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15,],[16,17,18,19,20],[21,22,23,24,25,]))
nums2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [32]:
print(nums2d[2:,1:])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW AS AN ARRAY
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [35]:
print(nums2d[3, 4])

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
print(nums2d[0:,1])

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
print(nums2d[4:,0:])

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [0]:
print(nums2d[3:,0:])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [43]:
mat = np.arange(1,26).reshape(5,5)
np.sum (mat)

325

#### Get the standard deviation of the values in mat

In [0]:
np.std(mat)

7.2111025509279782

#### Get the sum of all the columns in mat

In [5]:
mat.sum(axis=0)

AttributeError: module 'matplotlib' has no attribute 'sum'